name: 機能追加
description: 機能追加のフォームです。
title: "[feature]: "
labels: ["enhancement"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        次のフォームに従って、機能追加のIssueを作成します。
  - type: textarea
    id: as-is
    attributes:
      label: As-is
      description: 今の状態を記載してください。
    validations:
      required: true
  - type: textarea
    id: to-be
    attributes:
      label: To-be
      description: 理想の状態を記載してください。タスク完了の条件にもなります。
    validations:
      required: true
  - type: textarea
    id: action
    attributes:
      label: アクション
      description: 機能追加のための、具体的なアクションを記載してください。
    validations:
      required: true
  - type: textarea
    id:
    attributes:
      label: 課題
      description: 現状、分かっている課題を記載してください。
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: 参考
      description: 参考になりそうな、公式等のドキュメントやサイトを記載してください。
    validations:
      required: true
