name: ci
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]
jobs:
  e2e:
    # only runs this job on successful deploy
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
